# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\"_\n\x0e\x42ookingRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06origin\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65parture_time\x18\x04 \x01(\t\"E\n\x0c\x42ookingReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x12\n\nbooking_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2P\n\rClientManager\x12?\n\rSubmitBooking\x12\x17.booking.BookingRequest\x1a\x15.booking.BookingReply2M\n\tScheduler\x12@\n\x0eRequestJourney\x12\x17.booking.BookingRequest\x1a\x15.booking.BookingReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGREQUEST']._serialized_start=26
  _globals['_BOOKINGREQUEST']._serialized_end=121
  _globals['_BOOKINGREPLY']._serialized_start=123
  _globals['_BOOKINGREPLY']._serialized_end=192
  _globals['_CLIENTMANAGER']._serialized_start=194
  _globals['_CLIENTMANAGER']._serialized_end=274
  _globals['_SCHEDULER']._serialized_start=276
  _globals['_SCHEDULER']._serialized_end=353
# @@protoc_insertion_point(module_scope)
