# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\"\xc8\x01\n\x14\x43reateBookingRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x12\n\nvehicle_id\x18\x02 \x01(\t\x12\x16\n\x0eorigin_node_id\x18\x03 \x01(\x03\x12\x1b\n\x13\x64\x65stination_node_id\x18\x04 \x01(\x03\x12\x1b\n\x13\x64\x65parture_time_unix\x18\x05 \x01(\x03\x12\x1c\n\x14\x65stimated_duration_s\x18\x06 \x01(\x05\x12\x19\n\x11jurisdiction_code\x18\x07 \x01(\t\"\xd7\x02\n\x12GetBookingResponse\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x12\n\nvehicle_id\x18\x03 \x01(\t\x12\x16\n\x0eorigin_node_id\x18\x04 \x01(\x03\x12\x1b\n\x13\x64\x65stination_node_id\x18\x05 \x01(\x03\x12\x1b\n\x13\x64\x65parture_time_unix\x18\x06 \x01(\x03\x12\x1c\n\x14\x65stimated_duration_s\x18\x07 \x01(\x05\x12&\n\x06status\x18\x08 \x01(\x0e\x32\x16.booking.BookingStatus\x12\x19\n\x11jurisdiction_code\x18\t \x01(\t\x12\x10\n\x08route_id\x18\n \x01(\t\x12\x17\n\x0f\x63reated_at_unix\x18\x0b \x01(\x03\x12\x17\n\x0f\x65xpires_at_unix\x18\x0c \x01(\x03\x12\x0f\n\x07version\x18\r \x01(\x05*n\n\rBookingStatus\x12\x0b\n\x07PENDING\x10\x00\x12\r\n\tCONFIRMED\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x12\n\n\x06\x44\x45NIED\x10\x05\x12\x0b\n\x07\x45XPIRED\x10\x06\x32\\\n\rClientManager\x12K\n\rSubmitBooking\x12\x1d.booking.CreateBookingRequest\x1a\x1b.booking.GetBookingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGSTATUS']._serialized_start=575
  _globals['_BOOKINGSTATUS']._serialized_end=685
  _globals['_CREATEBOOKINGREQUEST']._serialized_start=27
  _globals['_CREATEBOOKINGREQUEST']._serialized_end=227
  _globals['_GETBOOKINGRESPONSE']._serialized_start=230
  _globals['_GETBOOKINGRESPONSE']._serialized_end=573
  _globals['_CLIENTMANAGER']._serialized_start=687
  _globals['_CLIENTMANAGER']._serialized_end=779
# @@protoc_insertion_point(module_scope)
