# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/scheduler.SchedulerService/CreateBooking',
                request_serializer=scheduler__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=scheduler__pb2.CreateBookingResponse.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/scheduler.SchedulerService/CancelBooking',
                request_serializer=scheduler__pb2.CancelBookingRequest.SerializeToString,
                response_deserializer=scheduler__pb2.CancelBookingResponse.FromString,
                _registered_method=True)
        self.GetBooking = channel.unary_unary(
                '/scheduler.SchedulerService/GetBooking',
                request_serializer=scheduler__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetBookingResponse.FromString,
                _registered_method=True)
        self.GetVehicleBookings = channel.unary_unary(
                '/scheduler.SchedulerService/GetVehicleBookings',
                request_serializer=scheduler__pb2.GetVehicleBookingsRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetVehicleBookingsResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=scheduler__pb2.CreateBookingRequest.FromString,
                    response_serializer=scheduler__pb2.CreateBookingResponse.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=scheduler__pb2.CancelBookingRequest.FromString,
                    response_serializer=scheduler__pb2.CancelBookingResponse.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=scheduler__pb2.GetBookingRequest.FromString,
                    response_serializer=scheduler__pb2.GetBookingResponse.SerializeToString,
            ),
            'GetVehicleBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleBookings,
                    request_deserializer=scheduler__pb2.GetVehicleBookingsRequest.FromString,
                    response_serializer=scheduler__pb2.GetVehicleBookingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/CreateBooking',
            scheduler__pb2.CreateBookingRequest.SerializeToString,
            scheduler__pb2.CreateBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/CancelBooking',
            scheduler__pb2.CancelBookingRequest.SerializeToString,
            scheduler__pb2.CancelBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetBooking',
            scheduler__pb2.GetBookingRequest.SerializeToString,
            scheduler__pb2.GetBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVehicleBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetVehicleBookings',
            scheduler__pb2.GetVehicleBookingsRequest.SerializeToString,
            scheduler__pb2.GetVehicleBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
